language: android
android:
  components:
    - android-20
    - build-tools-20.0.0

before_install:
  - chmod +x gradlew

# Attempt faster compiles.
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Extend compile timeout to 20 minutes; gwt easily takes 10+.
script: travis_wait ./gradlew clean build
